version: '3.8'
services:
  clickhouse:
    image: clickhouse/clickhouse-server
    ports:
      - 9000:9000
    environment:
      - CLICKHOUSE_USER
      - CLICKHOUSE_PASSWORD
    volumes:
      - ${PWD}/fs/volumes/clickhouse/etc/clickhouse-server/config.d/config.xml:/etc/clickhouse-server/config.d/config.xml
      - ${PWD}/fs/volumes/clickhouse/etc/clickhouse-server/users.d/users.xml:/etc/clickhouse-server/users.d/users.xml
      - ${PWD}/fs/volumes/clickhouse/docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d

  web:
    env_file:
      - .env
    depends_on:
      - clickhouse
    build:
      dockerfile: model.dockerfile
    environment:
      - CLICKHOUSE_USER
      - CLICKHOUSE_PASSWORD
    command: bash -c "python src/preprocess.py && python src/train.py && python src/predict.py -m LOG_REG -t func && coverage run src/unit_tests/test_preprocess.py && coverage run -a src/unit_tests/test_training.py && coverage report -m && python src/db_init.py && uvicorn src.app:app --host 0.0.0.0 --port 8000"
    ports:
      - 8000:8000
    image: papajool/big_data_lab2:latest




